Adding my home studio information
JakeGWater/vpifg.com pull request #14
Opened 2021-04-18 20:16 UTC by nvcexploder

2021-04-18 20:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JakeGWater/vpifg.com?pullRequest=14) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JakeGWater/vpifg.com?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JakeGWater/vpifg.com?pullRequest=14) it.</sub>

2021-04-20 15:18 UTC, JakeGWater requested changes
Awesome. Two asks:

1. I merged #15 which will let you annotate the page with your authorship info. Can you add that.
2. Can you reference your DIY green screen, even if you don't have instructions yet?
3. Can you reference your computer setup.

I mean 3 asks.

2021-04-20 15:47 UTC, nvcexploder commented
Definitely!

On Tue, Apr 20, 2021 at 11:18 AM JakeGWater ***@***.***>
wrote:

> *@JakeGWater* requested changes on this pull request.
>
> Awesome. Two asks:
>
>    1. I merged #15 <https://github.com/JakeGWater/vpifg.com/pull/15>
>    which will let you annotate the page with your authorship info. Can you add
>    that.
>    2. Can you reference your DIY green screen, even if you don't have
>    instructions yet?
>    3. Can you reference your computer setup.
>
> I mean 3 asks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JakeGWater/vpifg.com/pull/14#pullrequestreview-640087953>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACCRDHKDKF42F3EHCTAXPLTJWLM3ANCNFSM43ESOIOQ>
> .
>

2021-04-21 16:04 UTC, JakeGWater approved these changes

2021-04-21 16:05 UTC, merged